// Generated by CoffeeScript 1.5.0
(function() {
  var axis, exports, fs, stylus;

  stylus = require("stylus");

  axis = require("axis-css");

  fs = require("fs");

  exports = module.exports = function(path, outname, outpath, cb) {
    var file;
    if (!fs.existsSync(path + outname + ".styl")) {
      console.log("\x1B[0;31mAborting: Can't find " + outname + ".styl\x1B[0;0m");
      process.kill();
    }
    file = fs.readFileSync(path + outname + ".styl");
    return stylus(file.toString(), {
      compress: true
    }).set('paths', [path]).use(axis()).render(function(err, css) {
      var fileline, filename, i, line, linenumber, msg, output, reload;
      if (err) {
        msg = err.message.split("\n");
        fileline = msg.shift().split(":");
        linenumber = fileline.pop();
        filename = outname + ".styl";
        if (fileline[0] !== "stylus") {
          filename = fileline[0].split("/").pop();
        }
        for (i in msg) {
          line = msg[i];
          if (line.charAt(1) === ">") {
            msg[i] = "\x1B[0;1m" + line + "\x1B[0;0m";
          }
        }
        msg.pop();
        msg.push("\x1B[0;31m" + msg.pop() + "\x1B[0;0m");
        console.log("\x1B[0;31mError\x1B[0;0m in\x1B[0;1m " + filename + "\x1B[0;0m on line \x1B[0;1m" + linenumber + "\x1B[0;0m");
        console.log("````````````````````````````````````");
        console.log(msg.join("\n"));
        return console.log("````````````````````````````````````");
      } else {
        reload = true;
        if (!outpath) {
          output = path;
          reload = false;
        }
        if (outpath.charAt(outpath.length - 1) !== "/") {
          outpath = outpath + "/";
        }
        if (!fs.existsSync(outpath)) {
          fs.mkdirSync(outpath);
        }
        return fs.writeFile(outpath + outname + ".css", css, function() {
          console.log("Recompiled " + outname + ".styl");
          if (reload) {
            return cb(outpath + outname + ".css");
          }
        });
      }
    });
  };

}).call(this);
