// Generated by CoffeeScript 1.5.0
(function() {
  var axis, exports, fs, stylus;

  stylus = require("stylus");

  axis = require("axis-css");

  fs = require("fs");

  exports = module.exports = function(path) {
    var file;
    file = fs.readFileSync(path + "custom.styl");
    return stylus(file.toString()).set('paths', [path]).use(axis()).render(function(err, css) {
      var fileline, filename, i, line, linenumber, msg;
      if (err) {
        msg = err.message.split("\n");
        fileline = msg.shift().split(":");
        linenumber = fileline.pop();
        filename = "custom.styl";
        if (fileline[0] !== "stylus") {
          filename = fileline[0].split("/").pop();
        }
        for (i in msg) {
          line = msg[i];
          if (line.charAt(1) === ">") {
            msg[i] = "\x1B[0;1m" + line + "\x1B[0;0m";
          }
        }
        msg.pop();
        msg.push("\x1B[0;31m" + msg.pop() + "\x1B[0;0m");
        console.log("\x1B[0;31mError\x1B[0;0m in\x1B[0;1m " + filename + "\x1B[0;0m on line \x1B[0;1m" + linenumber + "\x1B[0;0m");
        console.log("````````````````````````````````````");
        console.log(msg.join("\n"));
        return console.log("````````````````````````````````````");
      } else {
        return fs.writeFile(path + "custom.css", css, function() {
          return console.log("\x1B[0;32mRecompiled custom.styl\x1B[0;0m");
        });
      }
    });
  };

}).call(this);
